<?php
$host = $_SERVER["HTTP_HOST"];
if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on"){
    $http = "https";
}
else{
    $http = "http";
}
$hostName = explode(".", $host)[0];
$hostCurrent = "www.divano.ru";
$sitemapName = "";
if ($host !== $hostCurrent) {
	$sitemapName = "/" . $hostName . "-sitemap";
} else {
	$sitemapName = "/sitemap";
}
header("Content-Type: text/plain");?>
User-Agent: *
Allow: /*.css
Allow: /*.js
Allow: /bitrix/components/
Allow: /bitrix/js/
Allow: /bitrix/panel/
Allow: /bitrix/templates/
Allow: */informacija/*?PAGEN_
Allow: /catalog/sale/$
Sitemap: http://www.divano.ru/sitemap.xml
Disallow: */?
Disallow: */besplatnaya-dostavka/*filter
Disallow: */delivery_date*/
Disallow: */filter/*-or-*/
Disallow: */filter/ucenka-utsenka/
Disallow: */mebel-s-dostavkoy-na-sleduyushchiy-den/
Disallow: */rasprodazha/*filter
Disallow: */v-rassrochku/*filter
Disallow: *-s-dostavkoy-na-sleduyushchiy-den
Disallow: /*.html
Disallow: /*/*ORDER_TYPE
Disallow: /*/_old/
Disallow: /*/filter/-
Disallow: /*/filter/$
Disallow: /*/filter/*-from-
Disallow: /*/filter/*-to-
Disallow: /*/filter/clear/
Disallow: /*/pagen/
Disallow: /*/provider_
Disallow: /*filter*type_section-
Disallow: /*filter/*/*/
Disallow: /*filter/*/*page
Disallow: /*filter/*price3
Disallow: /*filter/depth
Disallow: /*filter/height
Disallow: /*filter/length
Disallow: /*filter/splace_
Disallow: /*index.php
Disallow: /*page*/page
Disallow: /*pagen*/pagen
Disallow: /*textile
Disallow: /about/vakansii/
Disallow: /auth
Disallow: /bitrix/admin
Disallow: /catalog/brendy/*filter
Disallow: /catalog/compare/
Disallow: /catalog/novinki-mesyatsa/*filter
Disallow: /catalog/rasprodaja/*filter
Disallow: /catalog/sale/
Disallow: /catalog/stok/*filter
Disallow: /complects/filter/
Disallow: /index
Disallow: /credit/
Disallow: /order/
Disallow: /test.txt
Disallow: /wmail_
Disallow: */undefined/
Disallow: *skidk*/filter/
Disallow: *aktsiya*/filter/
Disallow: *rasprod*/filter/
Disallow: /*http:
Disallow: /*https:
Disallow: */www
Disallow: *&color
Disallow: *?color
Disallow: */divan-dins-velvet-yellow-test/
Disallow: /backup_xml
Sitemap: https://vladimir.divano.ru/vladimir-sitemap.xml
Sitemap: https://spb.divano.ru/sbp-sitemap.xml
Sitemap: https://www.divano.ru/sitemap.xml
Sitemap: https://yaroslavl.divano.ru/yaroslavl-sitemap.xml
Sitemap: https://ivanovo.divano.ru/ivanovo-sitemap.xml
Sitemap: https://nizhniy-novgorod.divano.ru/nizhniy-novgorod.xml

User-Agent: Yandex
Allow: /*.css
Allow: /*.js
Allow: /bitrix/components/
Allow: /bitrix/js/
Allow: /bitrix/panel/
Allow: /bitrix/templates/
Allow: */informacija/*?PAGEN_
Allow: /catalog/sale/$
Disallow: */?amp&
Disallow: */?&
Disallow: */?arrFilter_
Disallow: */besplatnaya-dostavka/*filter
Disallow: */delivery_date*/
Disallow: */filter/*-or-*/
Disallow: */filter/*-is-*/
Disallow: */filter/ucenka-utsenka/
Disallow: */mebel-s-dostavkoy-na-sleduyushchiy-den/
Disallow: */rasprodazha/*filter
Disallow: */v-rassrochku/*filter
Disallow: *-s-dostavkoy-na-sleduyushchiy-den
Disallow: /*.html
Disallow: /*/*ORDER_TYPE
Disallow: /*/_old/
Disallow: /*/filter/-
Disallow: /*/filter/$
Disallow: /*/filter/*-from-
Disallow: /*/filter/*-to-
Disallow: /*/filter/clear/
Disallow: /*/pagen/
Disallow: /*/provider_
Disallow: /*?$
Disallow: /*filter*type_section-
Disallow: /*filter/*/*/
Disallow: /*filter/*/*page
Disallow: /*filter/*price3
Disallow: /*filter/depth
Disallow: /*filter/height
Disallow: /*filter/length
Disallow: /*filter/splace_
Disallow: /*index.php
Disallow: /*page*/page
Disallow: /*pagen*/pagen
Disallow: /*textile
Disallow: /about/vakansii/
Disallow: /auth
Disallow: /bitrix/admin
Disallow: /catalog/brendy/*filter
Disallow: /catalog/compare/
Disallow: /catalog/novinki-mesyatsa/*filter
Disallow: /catalog/rasprodaja/*filter
Disallow: /catalog/sale/
Disallow: /catalog/stok/*filter
Disallow: /complects/filter/
Disallow: /index
Disallow: /credit/
Disallow: /catalog/?
Disallow: */detail.php
Disallow: */?cm_id
Disallow: /order/
Disallow: /test.txt
Disallow: /wmail_
Disallow: */undefined/
Disallow: *skidk*/filter/
Disallow: *aktsiya*/filter/
Disallow: *rasprod*/filter/
Disallow: /*http:
Disallow: /*https:
Disallow: */www
Disallow: */?=
Disallow: *&color
Disallow: *?color
Clean-param: __iloveadaptive-hash__&_opens&_openstat&_prr&_r&action&actual-format&ADD_TO_COMPARE_LIST&amp&arrFilter&attempt&avarta&b&back_url&back_url_admin&backurl&banner-test-tags&baobab_event_id&bg&bitrix_include_areas&by&category_matrasov&change_password&clear_cache
Clean-param: clear_cache_session&clid&clkt&cm_id&color&colors&components&cr_osobennosti&cr_stil_mebeli&cr_vid_divana&cto_pld&cz&depth_main_from&depth_main_to&digiPreview&email&etext&fast&field&forgot_password&form_stol_k&format-type&frame&from&frommarket&hcb&height_main_from
Clean-param: height_main_to&hl&how&id&Itemid&lang&length_main_from&length_main_to&limitstart&login&logout&material&new_card&no_watermark&nx&ny&order&ORDER_BY&ORDER_TYPE&otype&page&PAGEN_10&PAGEN_109&PAGEN_11&PAGEN_127&PAGEN_13&PAGEN_131&PAGEN_21&PAGEN_22&PAGEN_23&PAGEN_24
Clean-param: PAGEN_25&PAGEN_26&PAGEN_27&PAGEN_3&PAGEN_30&PAGEN_31&PAGEN_36&PAGEN_38&PAGEN_39&PAGEN_4&PAGEN_40&PAGEN_43&PAGEN_49&PAGEN_5&PAGEN_50&PAGEN_51&PAGEN_6&PAGEN_67&PAGEN_69&PAGEN_7&PAGEN_73&PAGEN_75&PAGEN_8&PAGEN_81&PAGEN_89&payment_type&pm_block&pm_campaign_id
Clean-param: pm_keyword&pm_position&pm_source&pop&price_from&price_to&print&print_course&proizvod&provider_1&q&register&replyid&roistat_visit&rs&rs_stat&s&sale&section&SECTION_ID&set_filter&show_include_exec_time&show_page_exec_time&show_sql_stat&SHOWALL&SHOWALL_1&SIZEN&SIZEN_&smartleads_pid&smartleads_sid&smartleads_src&sort&spell&splace_length_main_from&splace_length_main_to
Clean-param: splace_width_main_from&splace_width_main_to&stat-id&table_form&target-ref&test-tag&tpl&transformation&tvtables_features&type&type_section&uid&utm_campaign&utm_content&utm_medium&utm_referrer&utm_sitelink&utm_source&utm_term&wprid&y_ref&yadclid&yadordid
Clean-param: yandex_ad_client_id&yandex_ad_order_id&yhid&format&height&mailtrackingid&pagen_2&product_id&r&sasasas&scale&sdebug&to
Clean-param: roistat&roistat_referrer&roistat_pos&rb_clickid&pid&limit&skip&rr_linkid&MailTrackingId&rr_productId&fast_order&rr_linkpos&t&fbclid&categoryId&from_completions&d&back&sortBy&sortDest&wewewe&msclkid&RESULT_ID&WEB_FORM_ID&formresult&material_kompanjon&subid&67676
Clean-param: sa&ved&length_to&esrc&rct&usg&SHOWALL_2&coupon_clear&frm&length_from&target&erere&PAGEN_100&TT&adv&click-link&cr_divany&dlina_v_razlog_vide&e&erer&qw&alfa&width&price2_from&price2_to&sorting&wewe
Clean-param: ab&a&filler&text&external_browser_redirect&tip_fasada&podlokotniki&utm_expid&use_geo&campaign_id&adgroupid&creative&placement&feeditemid&network&PAGEN_2

User-Agent: Googlebot
Allow: /*.css
Allow: /*.js
Allow: /bitrix/components/
Allow: /bitrix/js/
Allow: /bitrix/panel/
Allow: /bitrix/templates/
Allow: */informacija/*?PAGEN_
Allow: /catalog/sale/$
Disallow: */?amp&
Disallow: */?&
Disallow: */?arrFilter_
Disallow: */besplatnaya-dostavka/*filter
Disallow: */delivery_date*/
Disallow: */filter/*-or-*/
Disallow: */filter/ucenka-utsenka/
Disallow: */mebel-s-dostavkoy-na-sleduyushchiy-den/
Disallow: */rasprodazha/*filter
Disallow: */v-rassrochku/*filter
Disallow: *-s-dostavkoy-na-sleduyushchiy-den
Disallow: /*.html
Disallow: /*/*ORDER_TYPE
Disallow: /*/_old/
Disallow: /*/filter/-
Disallow: /*/filter/$
Disallow: /*/filter/*-from-
Disallow: /*/filter/*-to-
Disallow: /*/filter/clear/
Disallow: /*/pagen/
Disallow: /*/provider_
Disallow: /*?$
Disallow: /*filter*type_section-
Disallow: /*filter/*/*/
Disallow: /*filter/*/*page
Disallow: /*filter/*price3
Disallow: /*filter/depth
Disallow: /*filter/height
Disallow: /*filter/length
Disallow: /*filter/splace_
Disallow: /*index.php
Disallow: /*page*/page
Disallow: /*pagen*/pagen
Disallow: /*textile
Disallow: /about/vakansii/
Disallow: /auth
Disallow: /bitrix/admin
Disallow: /catalog/brendy/*filter
Disallow: /catalog/compare/
Disallow: /catalog/novinki-mesyatsa/*filter
Disallow: /catalog/rasprodaja/*filter
Disallow: /catalog/sale/
Disallow: /catalog/stok/*filter
Disallow: /complects/filter/
Disallow: /index
Disallow: /credit/
Disallow: /catalog/?
Disallow: */detail.php
Disallow: */?cm_id
Disallow: /order/
Disallow: /test.txt
Disallow: /wmail_
Disallow: */undefined/
Disallow: *skidk*/filter/
Disallow: *aktsiya*/filter/
Disallow: *rasprod*/filter/
Disallow: /*http:
Disallow: /*https:
Disallow: */www
Disallow: */?=
Disallow: *&color
Disallow: *?color
Sitemap: <?=$http?>://<?=$host?>/sitemap_dyn.php